---
title: "The ethnic origins and number of Holocaust victims killed at Auschwitz concentration camp"
author: 
  - Yang Zhou
thanks: "Link to the shiny app at :<https://zhouya76.shinyapps.io/victims/>. Code and data are available at: <https://github.com/yangzhoucoco/Holocaust-victims.git>. "
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
---
  Jamelle Bouie provides a deep reflection on the historical dismension of understanding the tran-Atlantic slave trade. There was about estimated 12.5 million people experienced this slave trade, of whom approximately 10.7 million survived to reach the Western Hemisphere. They use statistical data to show the slave trade impact on human. SlaveVoyages is the tools to provides the information about voyages and the internal dynamics of the trade within the United States. Besides, the article also talks about the ethical consideration. On one hand, the researchers need to look at numbers and data to understand the big picture of slavery—like how many people were enslaved and transported and require them to focus on the facts and figures. On the other hand, people lives are more than number. It's really important to remember that the researchers are talking about real people who had their own lives, feelings, and experiences. These individuals went through unimaginable suffering, and their stories are more than just numbers in a database. The researcher need to balance the two needs: the need to analyze the data to understand slavery as a historical phenomenon, and the need to respect and honor the humanity of the people who were enslaved.
  When I am creating a Shiny app for Holocaust victim data, although the contexts of the trans-Atlantic slave trade and the Holocaust are different, I also need to remember the balance between analyze data and ethical consideration. When I am creating Holocaust database and the graphs for the victims, I need to always keep in mind that the number is not only have the statistical meaning, but also it represent indivdual suffering. It is crucial for me to utilize digital tools and quantitative methods to study these atrocities, and also preserve the memory and humanity of each individual who suffered. Always to be respectful for the victims when I am describing the data. Bouie also talk about how SlaveVoyages change the people understanding of trade slave, this reminds me about the power of data and how the data educate the public and serve as an important source for research. This is similar to how  a database for Holocaust victims can serve as a vital resource for education and research, which can bring historical data to the public and build the connections between the public. I understand that database is not a series of number. It has a large potential for human development. When I am collecting and interpreting the related data, I need to ensure that the way I express is respectful and satisfy their need for sensitivity. 
  Bouie also mentioned about how SlaveVoyages database offers opportunities for descendants of enslaved individuals to connect with their ancestry, Holocaust victims database can serve for similar purpose. The project will contribute the community in a healing and remembrance way, which counter the forces of forgetting. For example, when I am interpreting Holocaust victims, I need to first recognize that each Number as Representing Individual Lives: Each figure—1,000,000 Jews, 70,000 Poles, 21,000 Romani, 14,000 Soviet POWs, and 12,000 victims from other groups—represents individual human beings with their own stories, families, dreams, and aspirations.Besides, the diversity of victimhood affect that the Holocaust affected a wide range of groups, each targeted for different reasons under the Nazi regime's ideology. In addition, I would avoid to use any language that would trivialize their suffering, so I might not compare the victims numbers because no matter the size of the victims, they are lives. The people's suffering will not change with the size of victims. After that, I will use the data as a tool to educate the public in order to honor the memory of the victims and contribute to ensuring that such atrocities are not forgotten and never repeated. Besides, I have to admit the limitation of the number, no matter how accurately the number compiled, it cannot capture the people pain and the depth of loss. The numbers are not tell us "how many", but they convey "how" and "why" of each victims suffer.
